services:
  - docker

env:
  global:
    - IMAGE=qgis/qgis

  matrix:
    - QGIS_VERSION_TAG=release-3_4
    - QGIS_VERSION_TAG=release-3_10

language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

addons:
  apt:
    packages:
      - git
      - python-software-properties

before_install:
  - docker pull ${IMAGE}:${QGIS_VERSION_TAG}

install:
  - pip install --upgrade pip
  - pip install --upgrade pylint
  - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 ${IMAGE}:${QGIS_VERSION_TAG}
  - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh qrbarcodeitem"

  - docker exec -it qgis-testing-environment sh -c "rm -f  /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qrbarcodeitem"
  - docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory/qrbarcodeitem /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qrbarcodeitem"

  - docker exec -it qgis-testing-environment sh -c "pip3 install -r /tests_directory/requirements.txt"

script:

  - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh qrbarcodeitem.test.test_suite"

sudo: false