name: CI Workflow

on:
  push:
    branches:
      - master
           
jobs:
  test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:final-3_14_1
      env:
        DISPLAY: ":99"

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            python3 -m pip3 install --upgrade pip
            python3 -m pip3 install -r requirements.txt