name: QR Barcode Plugin CI Workflow

on:
  push:
    branches:
      - master
           
jobs:
  test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:final-3_14_1
      env:
        DISPLAY: ":99"

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: python version
        run: python3 --version

      - name: pip version
        run: pip3 --version