name: QR Barcode Plugin CI Workflow

on:
  push:
    branches:
      - master
           
jobs:
  test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:final-3_14_1
      env:
        DISPLAY: ":99"

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup plugin
        run: qgis_setup.sh qrcodeitem